# Generated by Django 3.2.11 on 2022-01-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_merge_20220124_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Описание'),
        ),
    ]
